name: Build and Run Tests
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    inputs:
      chart_dir:
        required: true
        type: string
      chart_tag:
        required: false
        type: string
      chart_overwrite:
        required: true
        type: boolean
      is_lib_chart:
        required: false
        type: boolean
        default: false
      # chart_name Deprecated
      chart_name:
        required: false
        type: string
      pre_build_script:
        required: false
        type: string
      git_branch:
        required: false
        type: string
        default: ''      

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  process-charts:
    runs-on: ubuntu-latest
    outputs:
      gpt-version: ${{ steps.gpt-chart-version.outputs.chart-version }}
      agent-flows-version: ${{ steps.agent-flows-chart-version.outputs.chart-version }}
    env:
      REGISTRY: ghcr.io
      DOCKER_HUB_USER: owolabialiu
      HELM_TEMPLATE: template.yaml
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git_branch }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Run Pre-Build User-defined script
        run: bash -c '${{ inputs.pre_build_script }}'

      - name: Generate Docs
        continue-on-error: true
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
        uses: docker://jnorwood/helm-docs:v1.11.0
        with:
          entrypoint: helm-docs
          args: -g $(basename ${{ inputs.gpt_chart_dir }})
      - name: Install Dependencies
        run: helm dep build ${{ inputs.chart_dir }} --skip-refresh
      - name: Helm Lint
        run: helm lint ${{ inputs.chart_dir }}
      - name: Generate template.yaml
        if: ${{ !inputs.is_lib_chart }}
        run: helm template ${{ inputs.chart_dir }} > ${{ inputs.chart_dir }}/$HELM_TEMPLATE && cat ${{ inputs.chart_dir }}/$HELM_TEMPLATE
      - name: KubeVal Kubernetes Objects
        if: ${{ !inputs.is_lib_chart }}
        run: >
          docker run --rm -v $(pwd)/${{ inputs.chart_dir }}:/data
          cytopia/kubeval
          $HELM_TEMPLATE
          --output=stdout
          --strict
          --ignore-missing-schemas
      - run: rm -f $HELM_TEMPLATE
        if: ${{ !inputs.is_lib_chart }}
      - name: Get Chart Name from Chart.yaml
        run: echo "CHART_NAME=$(yq eval .name ${{ inputs.chart_dir }}/Chart.yaml)" >> $GITHUB_ENV
      - name: Get Chart Tag/version from Chart.yaml if not inputted
        if: ${{ inputs.chart_tag == '' }}
        run: echo "CHART_TAG=$(yq eval .version ${{ inputs.chart_dir }}/Chart.yaml)" >> $GITHUB_ENV
      - name: Chart Registry Overwrite Protection
        if: ${{ inputs.chart_overwrite == false }}
        run: '! $(helm pull oci://$REGISTRY/chart/$CHART_NAME --version $CHART_TAG)'
      - name: Release Helm Chart
        uses: appany/helm-oci-chart-releaser@v0.4.0
        with:
          name: ${{ env.CHART_NAME }}
          repository: owolabi16/charts
          tag: ${{ env.CHART_TAG }}
          path: ${{ inputs.chart_dir }}
          registry: ghcr.io
          registry_username: Owolabi16
          registry_password: ${{ secrets.PAT_TOKEN }}
        env:
          HELM_EXPERIMENTAL_OCI: 1

  build-gpt-image:
    needs: 'process-charts'
    uses: ./.github/workflows/build-image.yaml
    with:
      docker-arch: linux/arm64
      # custom-image-tag: ${{ needs.gpt-version.outputs.app-image-tag-version }}
    secrets:
      docker-build-secrets: "github_pat=${{ secrets.GHA_BOT_REPO_TOKEN }}"
      # DOCKER_HUB_TOKEN2: "${{ secrets.DOCKER_HUB_TOKEN2 }}"
      DOCKER_HUB_TOKEN: "${{ secrets.DOCKER_HUB_TOKEN }}"
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  
  build-agent-flows-image:
    needs: 'process-charts'
    uses: ./.github/workflows/build-image.yaml
    with:
      docker-arch: linux/arm64
      # dockerfile-path: "./Dockerfile.agentflows"
      # custom-image-name: agent-flows
      # custom-image-tag: ${{ needs.agent-flows-version.outputs.app-image-tag-version }}
    secrets:
      docker-build-secrets: "github_pat=${{ secrets.GHA_BOT_REPO_TOKEN }}"
      # DOCKER_HUB_TOKEN2: "${{ secrets.DOCKER_HUB_TOKEN2 }}"
      DOCKER_HUB_TOKEN: "${{ secrets.DOCKER_HUB_TOKEN }}"
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      
  build-migrate-vector-image:
    needs: 'process-charts'
    uses: ./.github/workflows/build-image.yaml
    with:
      docker-arch: linux/arm64
      # build-target: "migration"
      # custom-image-tag: ${{ needs.gpt-version.outputs.app-image-tag-version }}
    secrets:
      docker-build-secrets: "github_pat=${{ secrets.GHA_BOT_REPO_TOKEN }}"
      # DOCKER_HUB_TOKEN2: "${{ secrets.DOCKER_HUB_TOKEN2 }}"
      DOCKER_HUB_TOKEN: "${{ secrets.DOCKER_HUB_TOKEN }}"
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}      
      
  build-migrate-agent-image:
    needs: 'process-charts'
    uses: ./.github/workflows/build-image.yaml
    with:
      docker-arch: linux/arm64
      # build-target: "migration"
      # dockerfile-path: "./Dockerfile.agentflows"
      # custom-image-name: agent-flows
      # custom-image-tag: ${{ needs.agent-flows-version.outputs.app-image-tag-version }}
    secrets:
      docker-build-secrets: "github_pat=${{ secrets.GHA_BOT_REPO_TOKEN }}"
      # DOCKER_HUB_TOKEN2: "${{ secrets.DOCKER_HUB_TOKEN2 }}"
      DOCKER_HUB_TOKEN: "${{ secrets.DOCKER_HUB_TOKEN }}"
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}      

  docker-tests:
    name: Run Tests using Docker Image
    runs-on: ubuntu-latest
    needs: build-gpt-image
    timeout-minutes: 5
    env:
      DOCKER_REPO: ${{ needs.build-gpt-image.outputs.docker-repo }}
      DOCKER_TAG: ${{ needs.build-gpt-image.outputs.docker-tag }}
      DOCKER_TEST_IMAGE_TAG: gpt-search-test
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.hub.docker.com
          # username: owolabialiu
          username: aliuowolabi
          # password: ${{ secrets.DOCKER_HUB_TOKEN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN2 }}
      
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Pull Docker image
        run: docker pull --platform linux/arm64 $DOCKER_REPO:$DOCKER_TAG
      
      - name: Build Test Image
        run: >
          docker build
          --build-arg IMAGE=$DOCKER_REPO:$DOCKER_TAG
          -f Dockerfile
          -t $DOCKER_TEST_IMAGE_TAG .

      - name: Debug Docker Container
        run: |
          docker run $DOCKER_TEST_IMAGE_TAG find / -name "test_core.py" 2>/dev/null          
      
      - name: Execute Pytest
        run: |
          set -o pipefail
          docker run -v /tmp:/tmp -e PYTHONPATH=/app $DOCKER_TEST_IMAGE_TAG pytest ./gpt_search/test/ \
            --cov-report=xml:/tmp/coverage.xml \
            --cov-report=term \
            --junitxml=/tmp/pytest.xml \
            --cov=gpt_search | tee /tmp/pytest-coverage.txt
      
      - name: Pytest coverage comment
        if: always()
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: /tmp/coverage.xml
          junitxml-path: /tmp/pytest.xml
          title: Coverage Report
          badge-title: Coverage